### ISSUE TITLE
Can view potentially damaging files

### ISSUE THREAD

**Issue by lloydwatkin** [ONSdigital/babbage#1]
Its possible to view potentially damaging files such as:
- http://beta.ons.gov.uk/package.json
- http://beta.ons.gov.uk/node_modules/ONS-Pattern-Library/package.json

Whilst these aren't dangerous in themselves it does allow users to start finding out more about your systems (of course if its all open source this is also a moot point).

**Comment by Crispioso** [comment]
We're doing a bit of housekeeping and realised this issue was still open, oops! Thanks for the feedback but we're that since all of the code is open source we're fine with this risk. So we're going to close this issue.
